In [2]:
import numpy as np
import scipy
import sklearn
import lightgbm
import csv
import os
import pandas as pd
import seaborn

In [4]:
df = pd.read_csv('data/stanford_blueprint_datathon_2019_data.csv')

In [11]:
uniques = df.nunique()

In [12]:
print(uniques)

age                                                                                   7
gender                                                                                2
state                                                                                51
income                                                                               36
education                                                                             5
high_speed_internet_users                                                             3
technology_and_connectivity__online_gamers                                        89613
technology_and_connectivity__stream_music                                         89221
technology_and_connectivity__science_&_new_tech_enthusiasts                       94113
technology_and_connectivity__owns_apple_products                                  89897
technology_and_connectivity__smart_phone_owners                                   85784
technology_and_connectivity__download_videos                                      87745
technology_and_connectivity__stream_videos                                        89284
technology_and_connectivity__electronics_enthusiast                               96391
wearable_technology_and_connectivity_users                                            3
smart_phone_users                                                                     3
restaurant_app_users                                                                  3
services_software_and_online_services__genealogy_research_service_paid_users      83893
services_software_and_online_services__online_review_services_paid_users          79634
services_software_and_online_services__graphic_design_software_paid_users         82353
services_software_and_online_services__online_dating_paid_users                   78810
services_software_and_online_services_frequency                                       3
services_software_and_online_services_spend                                           3
restaurants_genres__ice_cream_restaurant_customers                                94221
restaurants_genres__italian_restaurant_customers                                  94281
restaurants_genres__steakhouse_customers                                          94017
restaurants_genres__pizza_restaurant_customers                                    95450
restaurants_genres__coffee_shop_customers                                         95510
restaurants_genres__sandwich_&_sub_restaurant_customers                           95688
restaurants_genres__donut_shop_customers                                          94562
                                                                                  ...
restaurants_sit_down_casual_dining__upscale_casual_restaurant_customers           94329
restaurants_sit_down_casual_dining_frequency                                          3
restaurants_sit_down_casual_dining_spend                                              3
restaurants_sit_down_upscale_dining__upscale_asian_fusion_restaurant_customers    89341
restaurants_sit_down_upscale_dining__upscale_seafood_restaurant_customers         86957
restaurants_sit_down_upscale_dining__upscale_steakhouse_customers                 84349
restaurants_sit_down_upscale_dining_frequency                                         3
restaurants_sit_down_upscale_dining_spend                                             3
restaurants_fast_casual_dining_frequency                                              3
restaurants_fast_casual_dining_spend                                                  3
entertainment_movies__movie_renters                                               93987
entertainment_movies__small_&_independent_theater_customers                       94728
entertainment_movies__national_brand_theater_customers                            94046
entertainment_movies__online_movie_ticket_buyers                                  90858
entertainment_movies_frequency                                                        3
entertainment_movies_spend                                                            3
services_ride_sharing_spend                                                           3
services_ride_sharing_frequency                                                       3
coffee_enthusiasts                                                                    3
date                                                                                 20
chlamydia                                                                          2357
gential_warts                                                                      4351
gonorrhea                                                                          2505
herpes                                                                             6446
hpv                                                                                5315
other_std                                                                          5567
parasitic                                                                          3031
std_screen                                                                         8527
syphilis                                                                           3945
trich                                                                              3867
Length: 79, dtype: int64

In [13]:
dates = df.drop_duplicates(subset='date')

In [19]:
print(dates['date'].sort_values())

2     2014-01-01
14    2014-04-01
16    2014-07-01
10    2014-10-01
3     2015-01-01
13    2015-04-01
0     2015-07-01
19    2015-10-01
1     2016-01-01
11    2016-04-01
20    2016-07-01
15    2016-10-01
12    2017-01-01
5     2017-04-01
4     2017-07-01
6     2017-10-01
17    2018-01-01
7     2018-04-01
48    2018-07-01
18    2018-10-01
Name: date, dtype: object

In [23]:
print(df.groupby('date').agg(['count']).sort_values(by='date'))

              age gender  state income education high_speed_internet_users  \
            count  count  count  count     count                     count
date
2014-01-01  68580  68580  68580  68580     68580                     68574
2014-04-01  69399  69399  69399  69399     69399                     69396
2014-07-01  69777  69777  69777  69777     69777                     69771
2014-10-01  69174  69174  69174  69174     69174                     69170
2015-01-01  70024  70024  70024  70024     70024                     70015
2015-04-01  70169  70169  70169  70169     70169                     70167
2015-07-01  69493  69493  69493  69493     69493                     69490
2015-10-01  68894  68894  68894  68894     68894                     68893
2016-01-01  70165  70165  70165  70165     70165                     70157
2016-04-01  70108  70108  70108  70108     70108                     70104
2016-07-01  69271  69271  69271  69271     69271                     69264
2016-10-01  68103  68103  68103  68103     68103                     68098
2017-01-01  69008  69008  69008  69008     69008                     69003
2017-04-01  68668  68668  68668  68668     68668                     68662
2017-07-01  67666  67666  67666  67666     67666                     67661
2017-10-01  67265  67265  67265  67265     67265                     67261
2018-01-01  68774  68774  68774  68774     68774                     68767
2018-04-01  67813  67813  67813  67813     67813                     67805
2018-07-01  57082  57082  57082  57082     57082                     57079
2018-10-01  67374  67374  67374  67374     67374                     67371

           technology_and_connectivity__online_gamers  \
                                                count
date
2014-01-01                                      68580
2014-04-01                                      69399
2014-07-01                                      69777
2014-10-01                                      69174
2015-01-01                                      70024
2015-04-01                                      70169
2015-07-01                                      69493
2015-10-01                                      68894
2016-01-01                                      70165
2016-04-01                                      70108
2016-07-01                                      69271
2016-10-01                                      68103
2017-01-01                                      69008
2017-04-01                                      68668
2017-07-01                                      67666
2017-10-01                                      67265
2018-01-01                                      68774
2018-04-01                                      67813
2018-07-01                                      57082
2018-10-01                                      67374

           technology_and_connectivity__stream_music  \
                                               count
date
2014-01-01                                     68580
2014-04-01                                     69399
2014-07-01                                     69777
2014-10-01                                     69174
2015-01-01                                     70024
2015-04-01                                     70169
2015-07-01                                     69493
2015-10-01                                     68894
2016-01-01                                     70165
2016-04-01                                     70108
2016-07-01                                     69271
2016-10-01                                     68103
2017-01-01                                     69008
2017-04-01                                     68668
2017-07-01                                     67666
2017-10-01                                     67265
2018-01-01                                     68774
2018-04-01                                     67813
2018-07-01                                     57082
2018-10-01                                     67374

           technology_and_connectivity__science_&_new_tech_enthusiasts  \
                                                                 count
date
2014-01-01                                              68580
2014-04-01                                              69399
2014-07-01                                              69777
2014-10-01                                              69174
2015-01-01                                              70024
2015-04-01                                              70169
2015-07-01                                              69493
2015-10-01                                              68894
2016-01-01                                              70165
2016-04-01                                              70108
2016-07-01                                              69271
2016-10-01                                              68103
2017-01-01                                              69008
2017-04-01                                              68668
2017-07-01                                              67666
2017-10-01                                              67265
2018-01-01                                              68774
2018-04-01                                              67813
2018-07-01                                              57082
2018-10-01                                              67374

           technology_and_connectivity__owns_apple_products  ... chlamydia  \
                                                      count  ...     count
date                                                         ...
2014-01-01                                            68580  ...      6840
2014-04-01                                            69399  ...      6725
2014-07-01                                            69777  ...      7330
2014-10-01                                            69174  ...      6755
2015-01-01                                            70024  ...      6741
2015-04-01                                            70169  ...      7363
2015-07-01                                            69493  ...      6644
2015-10-01                                            68894  ...      5483
2016-01-01                                            70165  ...      5546
2016-04-01                                            70108  ...      5260
2016-07-01                                            69271  ...      5053
2016-10-01                                            68103  ...      4784
2017-01-01                                            69008  ...      4988
2017-04-01                                            68668  ...      4610
2017-07-01                                            67666  ...      4034
2017-10-01                                            67265  ...      3986
2018-01-01                                            68774  ...      3928
2018-04-01                                            67813  ...      3795
2018-07-01                                            57082  ...      2054
2018-10-01                                            67374  ...      3372

           gential_warts gonorrhea herpes    hpv other_std parasitic  \
                   count     count  count  count     count     count
date
2014-01-01         16067      6010  38855  28954     28155     12251
2014-04-01         16658      6242  39341  29620     29220     12520
2014-07-01         16973      6138  38618  29540     29892     13514
2014-10-01         15801      6255  39103  28900     29232     13163
2015-01-01         16071      6687  39913  29255     30617     12592
2015-04-01         16775      6616  39928  29268     30905     12416
2015-07-01         15918      6591  37745  27889     31007     12378
2015-10-01         16943      6494  37948  24613     30044     12237
2016-01-01         18374      6814  39652  24874     30951     11476
2016-04-01         18933      6768  39039  24818     30858     11384
2016-07-01         18182      6605  37266  23848     30548     11459
2016-10-01         17630      6149  37256  22337     29107     10664
2017-01-01         17994      6888  38688  22890     29847     10548
2017-04-01         17867      6839  37774  22436     29336     10009
2017-07-01         16327      6177  36393  21981     29587      9812
2017-10-01         14407      6052  36926  22540     28535      9245
2018-01-01         14744      5731  38562  23680     29711      8970
2018-04-01         14545      5309  37047  23325     29523      8380
2018-07-01          9542      3783  25847  15996     21257      5476
2018-10-01         13580      5635  37452  22851     28580      7784

           std_screen syphilis  trich
                count    count  count
date
2014-01-01      57368     9096  13673
2014-04-01      58524     9740  14561
2014-07-01      59299    10399  14583
2014-10-01      58247     9980  14483
2015-01-01      59245    10675  14089
2015-04-01      59704    10909  14078
2015-07-01      59186    10226  14003
2015-10-01      58827     9124  13824
2016-01-01      60701     9847  14156
2016-04-01      60895     9716  14075
2016-07-01      59796     9080  13564
2016-10-01      58139     9110  12809
2017-01-01      59278     9941  13073
2017-04-01      59189    10063  13180
2017-07-01      58125     9363  12975
2017-10-01      57443     9151  12505
2018-01-01      59203    10113  12477
2018-04-01      58434     9896  12365
2018-07-01      47717     6866   7824
2018-10-01      57737     9662  11913

[20 rows x 78 columns]